// <auto-generated />
// This file was generated by MPR.CodeGenTool on 
// Unit of Work implementation - Multi DbContext

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using MPR.SampleProject.Domain.Repositories;
using MPR.SampleProject.Domain.UnitOfWork;
using MPR.SampleProject.Infrastructure.Repositories;
using MPR.SampleProject.Infrastructure.Context;

namespace MPR.SampleProject.Infrastructure.UnitOfWork
{
    public partial class UnitOfWork : IUnitOfWork, IDisposable
    {
        private readonly DefaultContext _defaultcontext;

        public UnitOfWork(DefaultContext defaultcontext)
        {
            this._defaultcontext = defaultcontext;
        }

        private ICustomerRepository? _customerRepository;
        public ICustomerRepository CustomerRepository =>
            _customerRepository ??= new CustomerRepository(_defaultcontext);

        public async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
        {
            var total = 0;
            total += await _defaultcontext.SaveChangesAsync(cancellationToken);
            return total;
        }

        public void Dispose()
        {
            _defaultcontext.Dispose();
            GC.SuppressFinalize(this);
        }
    }
}