// <auto-generated />
using MPR.SampleProject.Application.Commands;
using MPR.SampleProject.Application.Dtos;
using MPR.SampleProject.Domain.Entities;
using MPR.SampleProject.Domain.Repositories;
using MPR.SampleProject.Domain.UnitOfWork;
using AutoMapper;
using MediatR;

namespace MPR.SampleProject.Application.CommandHandlers;

public class CreateCustomerCommandHandler : IRequestHandler<CreateCustomerCommand, CustomerResultModel>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IMapper _mapper;

    public CreateCustomerCommandHandler(IUnitOfWork unitOfWork, IMapper mapper)
    {
        _unitOfWork = unitOfWork;
        _mapper = mapper;
    }

    public async Task<CustomerResultModel> Handle(CreateCustomerCommand request, CancellationToken cancellationToken)
    {
        var entity = _mapper.Map<Customer>(request);
        await _unitOfWork.CustomerRepository.AddAsync(entity, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);
        return _mapper.Map<CustomerResultModel>(entity);
    }
}

public class UpdateCustomerCommandHandler : IRequestHandler<UpdateCustomerCommand, CustomerResultModel>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IMapper _mapper;

    public UpdateCustomerCommandHandler(IUnitOfWork unitOfWork, IMapper mapper)
    {
        _unitOfWork = unitOfWork;
        _mapper = mapper;
    }

    public async Task<CustomerResultModel> Handle(UpdateCustomerCommand request, CancellationToken cancellationToken)
    {
        var existing = await _unitOfWork.CustomerRepository.GetByIdAsync(
            request.Id,
            cancellationToken);

        if (existing == null)
        {
            // Manejo de error
        }

        _mapper.Map(request, existing);

        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return _mapper.Map<CustomerResultModel>(existing);
    }
}

public class DeleteCustomerCommandHandler : IRequestHandler<DeleteCustomerCommand, bool>
{
    private readonly IUnitOfWork _unitOfWork;

    public DeleteCustomerCommandHandler(IUnitOfWork unitOfWork)
    {
        _unitOfWork = unitOfWork;
    }

    public async Task<bool> Handle(DeleteCustomerCommand request, CancellationToken cancellationToken)
    {
        var existing = await _unitOfWork.CustomerRepository.GetByIdAsync(
            request.Id,
            cancellationToken);

        if (existing == null)
            return false;

        _unitOfWork.CustomerRepository.Remove(existing);
        await _unitOfWork.SaveChangesAsync(cancellationToken);
        return true;
    }
}