// <auto-generated />
// This file was generated by MPR.CodeGenTool on 
// Interface for Unit of Work

using System.Threading;
using System.Threading.Tasks;
using MPR.SampleProject.Domain.Repositories;

namespace MPR.SampleProject.Domain.UnitOfWork
{
    public interface IUnitOfWork
    {
        ICustomerRepository CustomerRepository { get; }

        Task<int> SaveChangesAsync(CancellationToken cancellationToken = default);
    }
}