// <auto-generated />
using AutoMapper;
using MPR.SampleProject.Application.Dtos;
using MPR.SampleProject.Domain.Entities;

namespace MPR.SampleProject.Application.Mappings;

public class CustomerProfile : Profile
{
    public CustomerProfile()
    {
        CreateMap<CustomerCreateModel, Customer>();

        CreateMap<CustomerUpdateModel, Customer>()
            .ForAllMembers(opt => opt.Condition((src, dest, srcMember) => srcMember != null));

        CreateMap<Customer, CustomerResultModel>();
    }
}