// <auto-generated />
// This file was generated by MPR.CodeGenTool on 
// Interface for Customer repository

using MPR.SampleProject.Domain.Entities;

namespace MPR.SampleProject.Domain.Repositories
{
    public interface ICustomerRepository : IGenericRepository<Customer>
    {
        // Add custom methods for CustomerRepository here if needed
    }
}