// <auto-generated />
namespace MPR.SampleProject.Application.Dtos;

public class CustomerCreateModel
{

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

}


public class CustomerUpdateModel
{

    public Guid Id { get; set; }


    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

}

public class CustomerResultModel
{

    public Guid Id { get; set; }


    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

}

