// <auto-generated />
using MediatR;
using MPR.SampleProject.Application.Dtos;

namespace MPR.SampleProject.Application.Queries;

public class GetCustomerByIdQuery : IRequest<CustomerResultModel>
{

    public Guid Id { get; set; }

}

public class GetCustomerListQuery : IRequest<IEnumerable<CustomerResultModel>>
{
}