// <auto-generated />
using MediatR;
using MPR.SampleProject.Application.Dtos;

namespace MPR.SampleProject.Application.Commands;

public class CreateCustomerCommand : IRequest<CustomerResultModel>
{

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

}

public class UpdateCustomerCommand : IRequest<CustomerResultModel>
{

    public Guid Id { get; set; }


    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime DateOfBirth { get; set; }

}

public class DeleteCustomerCommand : IRequest<bool>
{

    public Guid Id { get; set; }

}