// <auto-generated />
// This file was generated by MPR.CodeGenTool on 
// Repository for Customer

using Microsoft.EntityFrameworkCore;
using MPR.SampleProject.Domain.Entities;
using MPR.SampleProject.Domain.Repositories;

namespace MPR.SampleProject.Infrastructure.Repositories
{
    public class CustomerRepository : GenericRepository<Customer>, ICustomerRepository
    {
        public CustomerRepository(DbContext context) : base(context)
        {
        }
    }
}