// <auto-generated />
using MPR.SampleProject.Application.Dtos;
using MPR.SampleProject.Application.Queries;
using MPR.SampleProject.Domain.Repositories;
using MPR.SampleProject.Domain.UnitOfWork;
using AutoMapper;
using MediatR;

namespace MPR.SampleProject.Application.QueryHandlers;

public class GetCustomerByIdQueryHandler : IRequestHandler<GetCustomerByIdQuery, CustomerResultModel>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IMapper _mapper;

    public GetCustomerByIdQueryHandler(IUnitOfWork unitOfWork, IMapper mapper)
    {
        _unitOfWork = unitOfWork;
        _mapper = mapper;
    }

    public async Task<CustomerResultModel> Handle(GetCustomerByIdQuery request, CancellationToken cancellationToken)
    {
        var result = await _unitOfWork.CustomerRepository.GetByIdAsync(
            request.Id,
            cancellationToken);

        return _mapper.Map<CustomerResultModel>(result);
    }
}

public class GetCustomerListQueryHandler : IRequestHandler<GetCustomerListQuery, IEnumerable<CustomerResultModel>>
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IMapper _mapper;

    public GetCustomerListQueryHandler(IUnitOfWork unitOfWork, IMapper mapper)
    {
        _unitOfWork = unitOfWork;
        _mapper = mapper;
    }

    public async Task<IEnumerable<CustomerResultModel>> Handle(GetCustomerListQuery request, CancellationToken cancellationToken)
    {
        var result = await _unitOfWork.CustomerRepository.GetAllAsync(cancellationToken);
        return _mapper.Map<IEnumerable<CustomerResultModel>>(result);
    }
}