// <auto-generated />
// This file was generated by MPR.CodeGenTool on 
// DTO used for read/query operations for the Customer entity.

using System;

namespace MPR.SampleProject.Application.Dtos.Queries
{
    /// <summary>
    /// DTO for returning Customer data.
    /// </summary>
    public partial class CustomerDto
    {
        /// <summary>
        /// Id of the Customer.
        /// </summary>
        public Guid Id { get; set; }
        /// <summary>
        /// FirstName of the Customer.
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// LastName of the Customer.
        /// </summary>
        public string LastName { get; set; }
        /// <summary>
        /// DateOfBirth of the Customer.
        /// </summary>
        public DateTime DateOfBirth { get; set; }
    }
}